# Generated by Django 4.0 on 2021-12-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_calculator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calculator',
        ),
    ]
